import Head from 'next/head';
import Button from '@/components/Button';
import MainLayout from '@/layouts/MainLayout';
import { useTranslation } from 'react-i18next';
import TextField from '@/components/TextField';

export default function Home() {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>Ballr - Strona główna</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MainLayout>
        <div>
          <h1 className="text-heading-title-desktop text-green-900">
            {t('home-page.title')}
          </h1>
          <p>{t('home-page.subtitle')}</p>
        </div>
        <div className="flex h-[190px] flex-col items-center justify-center rounded-3xl bg-green-900">
          <p className="text-heading-h4 text-white">
            Wyszukaj zajęcia po lokalizacji
          </p>
          <div className="flex gap-2 rounded-full bg-white px-8 py-4">
            <TextField
              label="aaaa"
              placeholder="Lokalizacja"
              helperText="Helper text"
            />
            <Button value="Szukaj" onClick={() => console.log('Szukaj')} />
          </div>
        </div>
        <div>
          <p className="text-heading-h5">Honorujemy</p>
        </div>
        <section className="flex justify-between">
          <div>
            <h2 className="text-heading-h2">Czym jest Ballr?</h2>
            <p>
              Celem stworzenia aplikacji Ballr jest udostępnienie użytkownikom,
              zainteresowanym grą w piłkę nożną, możliwości łatwej i efektywnej
              organizacji meczów. Aplikacja celuje w grupy amatorskich
              miłośników tego sportu, którzy chcieliby z łatwością móc tworzyć
              grupy zawodników, umawiać terminy rozgrywek, wynajmować obiekty
              oraz tworzyć wydarzenia wraz ze społecznością.
            </p>
          </div>
          <div>
            <div className="h-[100px] w-[100px] bg-green-900">Placeholder</div>
            <div className="h-[100px] w-[100px] bg-green-900">Placeholder</div>
          </div>
        </section>
        <section className="space-y-8 bg-green-200">
          <div className="space-y-3">
            <h2 className="text-heading-h2">
              Stwórz drużynę marzeń i wygrywaj mecze
            </h2>
            <p>Rezerwuj i graj ze swoją drużyną za pomocą kilku kliknięć!</p>
          </div>
          <Button
            value="Zarejestruj się"
            onClick={() => console.log('Zarejestruj się')}
          />
        </section>
      </MainLayout>
    </>
  );
}
